update pull request of historicPage
Devseptomerveille/BOM2-Test pull request #13
Opened 2024-02-08 09:52 UTC by Devseptomerveille

2024-02-16 14:35 UTC, mloic47 requested changes

2024-02-16 14:35 UTC, mloic47 commented on cypress/e2e/tests/historicTest.cy.js
> +    cy.visit("https://adminbom.smobilpay.integration.maviance.info/agent-payments?filter=")
CREATE A FIXTURE FILE USER.JSON AND ENTER ALL YOUR USER CREDENTIALS IN THERE

2024-02-16 14:35 UTC, mloic47 commented on cypress/e2e/tests/historicTest.cy.js
> +      cy.contains( historicPage.click_collected_amount_ident ,"Collected Amount").click()
all these plain text should be in a fixture file

2024-02-16 15:04 UTC, Devseptomerveille commented
Ok I’m working on it

On Fri, 16 Feb 2024 at 3:36 PM, Le Roy Loic Mewoulou <
***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In cypress/e2e/tests/historicTest.cy.js
> <https://github.com/Devseptomerveille/BOM2-Test/pull/13#discussion_r1492553727>
> :
>
> > +//import historicPage identifiers
> +import {HistoricPage} from "../pages/HistoricPage"
> +//import page identifiers
> +const historicPage = new HistoricPage
> +
> +let testData = null;
> +let test_filePath = "testdata.json"
> +
> +describe("assert that the user can click history in the bar distribution side menu", () =>{
> +  before(() => {
> +    cy.readJsonFile(test_filePath).then((data) => {
> +      testData =data
> +    })
> +  })
> +  beforeEach(() => {
> +    cy.visit("https://adminbom.smobilpay.integration.maviance.info/agent-payments?filter=")
>
> CREATE A FIXTURE FILE USER.JSON AND ENTER ALL YOUR USER CREDENTIALS IN
> THERE
> ------------------------------
>
> In cypress/e2e/tests/historicTest.cy.js
> <https://github.com/Devseptomerveille/BOM2-Test/pull/13#discussion_r1492554942>
> :
>
> > +      cy.get(loginPage.button_login_field).click()
> +      cy.get(historicPage.click_historic_field).click()
> +      cy.wait(500)
> +
> +  })
> +
> +  it ("the elements contained in the table of the historical page", () =>{
> +
> + //cy.get('.css-1fyoe53 > .MuiToolbar-root')
> +  //.get('.css-1fyoe53 > .MuiToolbar-root > :nth-child(1)',"EXPORT EXCEL").click()
> +   //.get('.css-1fyoe53 > .MuiToolbar-root > :nth-child(2)',"EXPORT CSV").click()
> +      cy.log('** Service not sortable**').wait(500)
> +      cy.contains( historicPage.click_service_ident,"Service").click()
> +      cy.get( historicPage.destination_ident).contains("Destination")
> +      cy.log('** Collected Amount is not sortable**').wait(500)
> +      cy.contains( historicPage.click_collected_amount_ident ,"Collected Amount").click()
>
> all these plain text should be in a fixture file
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Devseptomerveille/BOM2-Test/pull/13#pullrequestreview-1885296346>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BELCTH47OFVYOXBGYV74T6DYT5VFJAVCNFSM6AAAAABC7NMI22VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTQOBVGI4TMMZUGY>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-02-19 11:51 UTC, mloic47 approved these changes

2024-02-19 11:51 UTC, merged